from abc import ABC, abstractmethod

class ReportTemplate(ABC):

    def generate_report(self):
        self.parse_data()
        self.validate_data()
        if self.needs_revalidation():
            self.revalidate_data()
        self.save_report()

    def parse_data(self):
        print("Parsing data for the report...")

    def validate_data(self):
        print("Validating data before generating report...")

    def revalidate_data(self):
        print("Revalidating data for special report...")

    @abstractmethod
    def save_report(self):
        pass

    def needs_revalidation(self):
        return False


class PDFReport(ReportTemplate):
    def save_report(self):
        with open("report.pdf", "w") as file:
            file.write("This is a PDF Report generated by the program.")
        print("PDF file generated successfully.")


class DOCXReport(ReportTemplate):
    def save_report(self):
        with open("report.docx", "w") as file:
            file.write("This is a DOCX Report generated by the program.")
        print("DOCX file generated successfully.")


class TXTReport(ReportTemplate):
    def save_report(self):
        with open("report.txt", "w") as file:
            file.write("This is a TXT Report generated by the program.")
        print("TXT file generated successfully.")


class CSVReport(ReportTemplate):
    def needs_revalidation(self):
        return True

    def save_report(self):
        with open("report.csv", "w") as file:
            file.write("Name,Score\nPriyanshu,98\nAryan,90")
        print("CSV file generated successfully.")


class JSONReport(ReportTemplate):
    def needs_revalidation(self):
        return True

    def save_report(self):
        with open("report.json", "w") as file:
            file.write('{"name": "Priyanshu", "score": 95}')
        print("JSON file generated successfully.")


def main():
    print("Welcome to Report Generator")
    print("1. PDF")
    print("2. DOCX")
    print("3. TXT")
    print("4. CSV")
    print("5. JSON")

    choice = input("Choose report type: ")

    if choice == "1":
        report = PDFReport()
    elif choice == "2":
        report = DOCXReport()
    elif choice == "3":
        report = TXTReport()
    elif choice == "4":
        report = CSVReport()
    elif choice == "5":
        report = JSONReport()
    else:
        print("Invalid choice")
        return

    print("\nGenerating report...")
    report.generate_report()


if __name__ == "__main__":
    main()